development:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/tmp/jetty/solr/test-data"
  solr_server_url: "http://localhost:8888/solr"
test:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/tmp/jetty/solr/test-data"
  solr_server_url: "http://localhost:8888/solr"
production:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/data/solr/search-index"
  solr_server_url: "http://localhost:8080/solr"
