defaults: &defaults
  jetty_path: "/Users/wheels/Sites/java/jetty"
  solr_data_dir: "/Users/wheels/Sites/java/jetty/solr/test-data"
  solr_server_url: "http://localhost:9090/solr"
development:
  <<: *defaults
test:
  <<: *defaults
production:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/data/solr/eat2treat-data"
  solr_server_url: "http://localhost:8080/solr"
